package ichttt.battleship.logic;

import com.sun.istack.internal.NotNull;
import com.sun.istack.internal.Nullable;

/**
 * Created by Tobias on 14.12.2016.
 */

public class HitTable {
    public int[] posx, posy;
    private int i = 0;

    /**
     * Creates a new HitTable. Only one value may be null.
     * If one value is null, the other value will initialize with an empty array with the size of the other array
     * @param posx The position on the X-Axis
     * @param posy The position on the Y-Axis
     * @throws IllegalArgumentException if the arrays are not the same size
     * @throws NullPointerException if both values are null
     */
    public HitTable(@Nullable int posx[], @Nullable int posy[]) throws NullPointerException, IllegalArgumentException {
        if(posx == null&&posy==null)
            throw new NullPointerException("Both arguments are null!");
        if(posx.length!=posy.length)
            throw new IllegalArgumentException("The arguments are not the same size!");
        this.posx = posx;
        this.posy = posy;
    }

    public HitTable(@NotNull int shipTilesLength) {
        this.posx = new int[shipTilesLength];
        this.posy = new int[shipTilesLength];
    }

    /**
     * Sets the next values in the arrays and automatically forwards to the next pos
     * @param posx The x value
     * @param posy The y value
     * @throws IndexOutOfBoundsException If there is no more space available for the parameters
     */
    public void setPos(@NotNull int posx, @NotNull int posy) throws IndexOutOfBoundsException {
        this.posx[i] = posx;
        this.posy[i] = posy;
        i++;
    }

    /**
     * Converts the {@linkplain HitTable} into a {@linkplain String}, that can be send over the network.
     * To reverse this process, use {@link #decodeFormString(String)}
     */
    @NotNull
    public String encodeToString() {
        String table =  "";
        for(int i = 0;i<posx.length;i++) {
            table += "X" + posx[i] + "Y" + posy[i] + "n";
        }
        return table;
    }

    /**
     * Converts a {@linkplain String} into a {@linkplain HitTable}.
     * Its recommended to use this only on strings generated by {@link #encodeToString()}
     * @param input The string to transform
     * @return A new HitTable or null if the string is invalid
     */
    @Nullable
    public static HitTable decodeFormString(@NotNull String input) {
        String strings[] = input.split("n");
        HitTable hitTable = new HitTable(strings.length);
        for(String s:strings) {
            if(!s.startsWith("X"))
                return null;
            String split[] = s.split("Y");
            if(!split[0].startsWith("X"))
                return null;
            split[0] = split[0].substring(1);
            int posx = Integer.parseInt(split[0]);
            int posy = Integer.parseInt(split[1]);
            hitTable.setPos(posx, posy);
        }
        hitTable.encodeToString();
        return hitTable;
    }

    /**
     * Returns the size of the arrays in this field.
     * This is may be NOT the actual size of the content
     * @return The size
     */
    public int size() {
        assert posx.length==posy.length;
        return posx.length;
    }

    /**
     * Sets all positions of an array to a given value
     * @param posx The x value
     * @param posy The y value
     */
    public void setAllPos(int posx, int posy) {
        for(int i = 0;i<this.size();i++) {
            this.posx[i] = posx;
            this.posy[i] = posy;
        }
    }
}